name = "rwtest"
version = "0.1.0"
keywords = ["math"]

[[require]]
scope = "leanprover-community"
name = "mathlib"
rev = "v4.14.0"

[[lean_lib]]
name = "Test"
srcDir = "."
globs = ["Test.*"]

[lean]
version = "leanprover/lean4:v4.14.0"
